### ISSUE TITLE
encfsui-setup clean does not clean old configurations 

### ISSUE THREAD

**Issue by scottmeup** [bulletmark/encfsui#1]
I ran `encfsui-setup clean` without error but the previous uniquely named volumes were still present in the menu bar icon volumes list.

Deleting the file
`/Users/%username%/Library/Preferences/encfsgui Preferences`
resolved the issue. OSX 10.10.5

I'd love to see an option to remove individual volumes from the menu bar icon gui as part of the application. Thanks for making such a great tool.

**Comment by bulletmark** [comment]
Sorry but encfsgui is not encfsui. Have you got the wrong project?

**Comment by scottmeup** [comment]
Ah, my apologies. The mistake is mine.
