### ISSUE TITLE
if /usr/share/doc/encfsui does not yet exist, make throws error

### ISSUE THREAD

**Issue by ziegel** [bulletmark/encfsui#2]
I do believe this is not distro specific
If /usr/share/doc/encfsui does not exist, sudo make install encfsui-setup throws following error:
install: failed to access ‘/usr/share/doc/encfsui’: No such file or directory

I believe the solution will be around line 52 in encfsui-setup script:
install -CDv -m 644 -t $DESTDIR$DOCDIR README.md

That should be enclosed in an if structure testing for the existence of the directory.
If the directory doesn't exist, the setup script should create it.

**Comment by bulletmark** [comment]
What distro/system and versions are you running? Note the `-D` switch on the `install` command creates all directories as required so I can't imagine why that is not working for you? And if it is not working, you should be seeing an error reported on that line about that switch.

**Comment by bulletmark** [comment]
No response from @ziegel so closing ..
