### ISSUE TITLE
Support for gocryptfs

### ISSUE THREAD

**Issue by TheDcoder** [bulletmark/encfsui#6]
First of all, thanks for creating a simple but effective script to open an encrypted container with a GUI dialog.

I was wondering if you could add support for [gocryptfs](https://nuetzlich.net/gocryptfs/)? It aims to be a modern successor to encfs and it seems to be better in all aspects. Here is a short description of it from their own site:
> This project was inspired by EncFS and strives to fix its security issues while providing good performance, see the [Comparison](https://nuetzlich.net/gocryptfs/comparison) page for benchmarks.

**Comment by bulletmark** [comment]
Good suggestion. I wrote this tool for myself more than 12 years ago and even though I still use it very frequently I have been completely out of the loop with regards to encryption tool alternatives such as `gocryptfs` which I agree looks more modern and `encfs` [appears to be dormant](https://github.com/vgough/encfs#status) now.

I think I will re-design this tool to have a plugin architecture with two plugins initially, `gocryptfs` and `encfs` but potentially [others](https://nuetzlich.net/gocryptfs/comparison/) could get added.

I'm glad somebody else appreciates the very simple end-user interface! Of course I will keep it that way.

**Comment by bulletmark** [comment]
Actually, I have changed my mind. `encfs` is essentially depreciated so no point spending time on coding anything for it. I will depreciate this current project also and put a big banner in the README about that and point to a new project which I will create: `gocryptfs-ui`. I have already running for myself and it works well. I will post that new project up on github in a few days.

**Comment by TheDcoder** [comment]
Awesome, thanks for the quick response! Waiting for the new project to get published :smile:

**Comment by bulletmark** [comment]
All done. Created [gocryptfs-ui](https://github.com/bulletmark/gocryptfs-ui) project and added superceded note to [encfsui](https://github.com/bulletmark/encfsui).
